# Generated by Django 4.2 on 2023-05-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_puesto_de_comida_evaluacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='calificacion',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='calificacion_comida',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='calificacion_precio',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='calificacion_presentacion',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
