# Generated by Django 4.2 on 2023-05-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_evaluacion_calificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='comentario',
            field=models.TextField(blank=True),
        ),
    ]
