# Generated by Django 4.2 on 2023-05-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_evaluacion_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apodo',
        ),
        migrations.AddField(
            model_name='user',
            name='pronombre',
            field=models.CharField(choices=[('La', 'La'), ('El', 'El'), ('Le', 'Le'), ('Otro', 'Otro')], default='Otro', max_length=5),
            preserve_default=False,
        ),
    ]
