# Generated by Django 4.2 on 2023-06-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_comentario_evaluacion_dislikes_evaluacion_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacion',
            old_name='comentario',
            new_name='detalle',
        ),
        migrations.AddField(
            model_name='comentario',
            name='dislike_comentario',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comentario',
            name='es_util',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comentario',
            name='like_comentario',
            field=models.IntegerField(default=0),
        ),
    ]
