# Generated by Django 4.2 on 2023-06-28 23:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_rename_comentario_evaluacion_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
