# Generated by Django 4.2 on 2023-07-01 03:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_evaluacion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fechacomentario',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(),
        ),
    ]
