# Generated by Django 4.2 on 2023-07-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_comentario_fechacomentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto_de_comida',
            name='dueño',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
