# Generated by Django 4.2 on 2023-07-02 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_puesto_de_comida_dueño'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='usuario_dio_dislike',
            field=models.ManyToManyField(related_name='dislike_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='usuario_dio_like',
            field=models.ManyToManyField(related_name='like_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
