# Generated by Django 4.2 on 2023-07-04 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_evaluacion_usuario_dio_dislike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='likes',
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='usuario_dio_dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='usuario_dio_like',
            field=models.ManyToManyField(blank=True, related_name='like_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
