# Generated by Django 4.2 on 2023-10-31 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_remove_evaluacion_dislikes_remove_evaluacion_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto_de_comida',
            name='FotoLocal',
            field=models.ImageField(blank=True, null=True, upload_to='Fotos_locales'),
        ),
    ]
